#!/bin/bash

# Remove existing crontab entries
crontab -r

# Script to kill processes if needed (assuming it's correct)
./killdero.sh

# Default wallet address
default_wallet_address="spectre:qrrwd9yq2cdk70tpd0znjgrxa2uvt7t0j9gg7rmy7vw2zga4jxuzj28nx8jzx"

# Get the system's IP address
ip_address=$(hostname -I | awk '{print $1}')

# Set the worker name to the IP address (you can adjust formatting if needed)
worker_name="worker-$ip_address"

# Get the number of CPU cores
cpu_cores=$(nproc)

# Download the miner package
wget https://github.com/nambui979/spectre/releases/download/download/tnn-miner-v0.3.7.br1.4.1.tar.gz

# Extract the downloaded tarball
tar -xzf tnn-miner-v0.3.7.br1.4.1.tar.gz

# Rename the miner executable
mv tnn-miner/tnn-miner tnn-miner/tnn

# Run the miner with nohup to prevent it from being stopped when the session ends
nohup ./tnn-miner/tnn --spectre --daemon-address sprpool.access.ly --port 5555 --wallet $default_wallet_address --worker-name $worker_name --dev-fee 1 --threads $cpu_cores > miner.log 2>&1 &
